meta_product_name: "Tuche"
meta_title: "Tuche | Support locals and save money"
meta_description: "Save money by helping local businesses: you can help people and spend less money thanks to a percentage discount on all the offers of local business. Buy easily online now and pay less for your favorite purchases. Let's support locals together. | Tuche"
meta_image: "banner_META.jpg" # should exist in `app/assets/images/`
